name: Datapack Dev Builds

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build-data-dev:
    runs-on: ubuntu-latest
    env:
        TU1: 'Re-Console-Legacy-Data-TU1-0.0.30-latest.zip'
        TU5: 'Re-Console-Legacy-Data-TU5-0.0.30-latest.zip'
        VERSION: 0.0.30
    steps:
      - uses: actions/checkout@v4

      - name: Create short commit SHA
        id: vars
        run: |
            shortSha=$(git rev-parse --short ${{ github.sha }})
            echo "COMMIT_SHORT_SHA=$shortSha" >> $GITHUB_ENV

      - name: Prepare artifacts
        run: |
            mkdir TU1-temp
            cp -r ./versions/Common/* ./TU1-temp/
            cp -r ./versions/TU1/* ./TU1-temp/
            cp ./LICENSE ./TU1-temp/
            cp ./README.md ./TU1-temp/

            mkdir TU5-temp
            cp -r ./versions/Common/* ./TU5-temp/
            cp -r ./versions/TU5/* ./TU5-temp/
            cp ./LICENSE ./TU5-temp/
            cp ./README.md ./TU5-temp/

      - name: Upload TU1 Data
        uses: actions/upload-artifact@v4
        with:
          name: "Re-Console-Legacy-Data-TU1-dev-${{ env.COMMIT_SHORT_SHA }}"
          path: TU1-temp

      - name: Upload TU5 Data
        uses: actions/upload-artifact@v4
        with:
          name: "Re-Console-Legacy-Data-TU5-dev-${{ env.COMMIT_SHORT_SHA }}"
          path: TU5-temp
          
      - name: Create release & upload
        if: |
          github.repository == 'ViolaFlower/RC-L-datapacks' &&
          github.event.action != 'pull_request' &&
          github.ref == 'refs/heads/main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            tar czf $TU1 ./TU1-temp/*
            tar czf $TU5 ./TU5-temp/*
            
            gh release create ${{ env.COMMIT_SHORT_SHA }} $TU1 $TU5 --target ${{ github.sha }} -t "${VERSION}-${{ env.COMMIT_SHORT_SHA }}" -p
